# Basketball Player Quality MLP

This notebook implements a simple Multi-Layer Perceptron (MLP) that estimates a basketball player's quality from five integer ratings, each from 1 to 100:

- Speed
- Jump
- Shooting
- Intelligence
- Strength

The network has one hidden layer and produces one predicted player-quality score on the required 0-10 scale, displayed with one decimal place. It uses random weights and biases, sigmoid activation in both the hidden and output layers, and forward propagation to validate sample player ratings.

In [1]:
import numpy as np


def sigmoid(values: np.ndarray) -> np.ndarray:
    """Apply the sigmoid activation function element-wise."""
    return 1.0 / (1.0 + np.exp(-values))


def initialize_parameters(
    input_size: int,
    hidden_size: int,
    output_size: int,
    random_seed: int = 42,
) -> dict[str, np.ndarray]:
    """Initialize random weights and biases for a single-hidden-layer MLP."""
    np.random.seed(random_seed)

    parameters = {
        "weights_input_hidden": np.random.randn(input_size, hidden_size),
        "bias_hidden": np.random.randn(1, hidden_size),
        "weights_hidden_output": np.random.randn(hidden_size, output_size),
        "bias_output": np.random.randn(1, output_size),
    }
    return parameters


def forward_propagation(
    inputs: np.ndarray,
    parameters: dict[str, np.ndarray],
) -> dict[str, np.ndarray]:
    """Perform forward propagation through hidden and output layers."""
    hidden_weighted_sum = (
        np.dot(inputs, parameters["weights_input_hidden"]) + parameters["bias_hidden"]
    )
    hidden_activation = sigmoid(hidden_weighted_sum)

    output_weighted_sum = (
        np.dot(hidden_activation, parameters["weights_hidden_output"])
        + parameters["bias_output"]
    )
    output_activation = sigmoid(output_weighted_sum)

    cache = {
        "hidden_weighted_sum": hidden_weighted_sum,
        "hidden_activation": hidden_activation,
        "output_weighted_sum": output_weighted_sum,
        "output_activation": output_activation,
    }
    return cache

In [2]:
# Define a simple MLP architecture.
# Input layer: 5 basketball ratings, hidden layer: 4 units, output layer: 1 quality score.
input_layer_size = 5
hidden_layer_size = 4
output_layer_size = 1

parameters = initialize_parameters(
    input_size=input_layer_size,
    hidden_size=hidden_layer_size,
    output_size=output_layer_size,
    random_seed=42,
)

print("MLP architecture:")
print(f"Input layer units: {input_layer_size}")
print(f"Hidden layer units: {hidden_layer_size}")
print(f"Output layer units: {output_layer_size}")

print("\nParameter shapes:")
print("weights_input_hidden:", parameters["weights_input_hidden"].shape)
print("bias_hidden:", parameters["bias_hidden"].shape)
print("weights_hidden_output:", parameters["weights_hidden_output"].shape)
print("bias_output:", parameters["bias_output"].shape)

MLP architecture:
Input layer units: 5
Hidden layer units: 4
Output layer units: 1

Parameter shapes:
weights_input_hidden: (5, 4)
bias_hidden: (1, 4)
weights_hidden_output: (4, 1)
bias_output: (1, 1)


In [3]:
# Each row contains ratings in this order: speed, jump, shooting, intelligence, strength.
sample_inputs = np.array(
    [
        [82, 88, 79, 75, 84],
        [91, 86, 94, 89, 78],
        [68, 73, 70, 82, 76],
        [95, 92, 65, 71, 90],
        [74, 69, 85, 88, 72],
    ]
)

forward_cache = forward_propagation(sample_inputs, parameters)

# Scale the sigmoid output from 0-1 to the required player-quality range of 0-10.
quality_scores = np.round(forward_cache["output_activation"] * 10, 1)

print("Sample basketball-player ratings:")
print("Columns: speed, jump, shooting, intelligence, strength")
print(sample_inputs)

print("\nHidden layer weighted sums:")
print(np.round(forward_cache["hidden_weighted_sum"], 4))

print("\nHidden layer activations (sigmoid output):")
print(np.round(forward_cache["hidden_activation"], 4))

print("\nOutput layer weighted sums:")
print(np.round(forward_cache["output_weighted_sum"], 4))

print("\nPredicted player-quality scores (0-10):")
for player_number, quality_score in enumerate(quality_scores.flatten(), start=1):
    print(f"Player {player_number}: {quality_score:.1f}")

Sample basketball-player ratings:
Columns: speed, jump, shooting, intelligence, strength
[[82 88 79 75 84]
 [91 86 94 89 78]
 [68 73 70 82 76]
 [95 92 65 71 90]
 [74 69 85 88 72]]

Hidden layer weighted sums:
[[ -82.4284 -106.4045  -50.1041   -6.5998]
 [ -75.0673 -127.7136  -73.0853   -0.8115]
 [ -71.8485 -121.7467  -83.4994  -27.8797]
 [ -77.3799 -107.1957  -27.428    16.5649]
 [ -69.4706 -126.238   -99.5988  -26.5217]]

Hidden layer activations (sigmoid output):
[[0.     0.     0.     0.0014]
 [0.     0.     0.     0.3076]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     1.    ]
 [0.     0.     0.     0.    ]]

Output layer weighted sums:
[[-0.6001]
 [-0.4851]
 [-0.6006]
 [-0.2249]
 [-0.6006]]

Predicted player-quality scores (0-10):
Player 1: 3.5
Player 2: 3.8
Player 3: 3.5
Player 4: 4.4
Player 5: 3.5
