# MLP Task

This notebook implements a simple Multi-Layer Perceptron (MLP) with:

- Fixed input and output layer sizes
- One hidden layer
- Random weight and bias initialization
- Sigmoid activation in hidden and output layers
- Forward propagation and sample output validation

In [4]:
import numpy as np


def sigmoid(values: np.ndarray) -> np.ndarray:
    """Apply the sigmoid activation function element-wise."""
    return 1.0 / (1.0 + np.exp(-values))


def initialize_parameters(
    input_size: int,
    hidden_size: int,
    output_size: int,
    random_seed: int = 42,
) -> dict[str, np.ndarray]:
    """Initialize random weights and biases for a single-hidden-layer MLP."""
    np.random.seed(random_seed)

    parameters = {
        "weights_input_hidden": np.random.randn(input_size, hidden_size),
        "bias_hidden": np.random.randn(1, hidden_size),
        "weights_hidden_output": np.random.randn(hidden_size, output_size),
        "bias_output": np.random.randn(1, output_size),
    }
    return parameters


def forward_propagation(
    inputs: np.ndarray,
    parameters: dict[str, np.ndarray],
) -> dict[str, np.ndarray]:
    """Perform forward propagation through hidden and output layers."""
    hidden_weighted_sum = (
        np.dot(inputs, parameters["weights_input_hidden"]) + parameters["bias_hidden"]
    )
    hidden_activation = sigmoid(hidden_weighted_sum)

    output_weighted_sum = (
        np.dot(hidden_activation, parameters["weights_hidden_output"])
        + parameters["bias_output"]
    )
    output_activation = sigmoid(output_weighted_sum)

    cache = {
        "hidden_weighted_sum": hidden_weighted_sum,
        "hidden_activation": hidden_activation,
        "output_weighted_sum": output_weighted_sum,
        "output_activation": output_activation,
    }
    return cache

In [5]:
# Define a simple MLP architecture.
# Input layer: 3 units, hidden layer: 4 units, output layer: 2 units.
input_layer_size = 3
hidden_layer_size = 4
output_layer_size = 2

parameters = initialize_parameters(
    input_size=input_layer_size,
    hidden_size=hidden_layer_size,
    output_size=output_layer_size,
    random_seed=42,
)

print("MLP architecture:")
print(f"Input layer units: {input_layer_size}")
print(f"Hidden layer units: {hidden_layer_size}")
print(f"Output layer units: {output_layer_size}")

print("\nParameter shapes:")
print("weights_input_hidden:", parameters["weights_input_hidden"].shape)
print("bias_hidden:", parameters["bias_hidden"].shape)
print("weights_hidden_output:", parameters["weights_hidden_output"].shape)
print("bias_output:", parameters["bias_output"].shape)

MLP architecture:
Input layer units: 3
Hidden layer units: 4
Output layer units: 2

Parameter shapes:
weights_input_hidden: (3, 4)
bias_hidden: (1, 4)
weights_hidden_output: (4, 2)
bias_output: (1, 2)


In [6]:
# Sample input data (5 samples, each with 3 features).
sample_inputs = np.array(
    [
        [0.1, 0.5, 0.2],
        [0.7, 0.3, 0.9],
        [0.4, 0.8, 0.6],
        [0.9, 0.2, 0.1],
        [0.3, 0.4, 0.7],
    ]
)

forward_cache = forward_propagation(sample_inputs, parameters)

print("Sample input data:")
print(sample_inputs)

print("\nHidden layer weighted sums:")
print(np.round(forward_cache["hidden_weighted_sum"], 4))

print("\nHidden layer activations (sigmoid output):")
print(np.round(forward_cache["hidden_activation"], 4))

print("\nOutput layer weighted sums:")
print(np.round(forward_cache["output_weighted_sum"], 4))

print("\nFinal network outputs (sigmoid output layer):")
print(np.round(forward_cache["output_activation"], 4))

Sample input data:
[[0.1 0.5 0.2]
 [0.7 0.3 0.9]
 [0.4 0.8 0.6]
 [0.9 0.2 0.1]
 [0.3 0.4 0.7]]

Hidden layer weighted sums:
[[ 0.0807 -1.9357 -0.9632 -0.1194]
 [ 0.0969 -1.592  -1.2148  0.3149]
 [-0.0284 -1.8304 -0.4805  0.3814]
 [ 0.5952 -2.0303 -0.8725  0.9154]
 [-0.0313 -1.6686 -1.2233 -0.1244]]

Hidden layer activations (sigmoid output):
[[0.5202 0.1261 0.2762 0.4702]
 [0.5242 0.1691 0.2288 0.5781]
 [0.4929 0.1382 0.3821 0.5942]
 [0.6446 0.1161 0.2947 0.7141]
 [0.4922 0.1586 0.2274 0.4689]]

Output layer weighted sums:
[[-0.7491 -0.636 ]
 [-0.8544 -0.8385]
 [-0.5689 -0.8622]
 [-0.8224 -0.9344]
 [-0.822  -0.6779]]

Final network outputs (sigmoid output layer):
[[0.321  0.3462]
 [0.2985 0.3019]
 [0.3615 0.2969]
 [0.3053 0.282 ]
 [0.3053 0.3367]]
